### ISSUE TITLE
website_event_register_free: Error when trying to register on free event

### ISSUE THREAD

**Issue by sandraMARIONEX** [OCA/website#15]
Odoo V8

website_event_sale installed.
![image 2](https://cloud.githubusercontent.com/assets/10046359/6168695/bf5f7592-b2c7-11e4-85b2-a7144891f372.png)

New event created with no type of tickets. Ticket type free appears in webpage and when I click on Register now, I receive this: 500: Internal Server Error
Here is the trace:
Traceback (most recent call last):
  File "/home/openerp-sandbox8/instance/parts/odoo/addons/website/models/ir_http.py", line 204, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 654, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 672, in dispatch
    r = self._call_function(*_self.params)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 299, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 791, in __call__
    return self.method(_args, *_kw)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 395, in response_wrap
    response = f(_args, *_kw)
  File "/home/openerp-sandbox8/instance/website/website_event_register_free/controllers/website_event.py", line 51, in event_register_free
    'user_id': http.request.env.user.id,
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/connector/connector/producer.py", line 47, in create
    record_id = create_original(self, vals)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/models.py", line 4007, in create
    record = self.browse(self._create(old_vals))
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/models.py", line 4198, in _create
    recs._validate_fields(vals)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/models.py", line 1292, in _validate_fields
    raise ValidationError("Error while validating constraint\n\n%s" % tools.ustr(e))
ValidationError: ('ValidateError', u'Error while validating constraint\n\nNo more available seats.')

However, minimum  and maximum available seats are defined. 
![image 1](https://cloud.githubusercontent.com/assets/10046359/6168653/4be4c734-b2c7-11e4-961c-919ee05919a0.png)
![image 2](https://cloud.githubusercontent.com/assets/10046359/6168705/d49c5e02-b2c7-11e4-95ad-61bab5a6f575.png)

**Comment by pedrobaeza** [comment]
It seems that you haven't configured max seats of the event.

**Comment by sandraMARIONEX** [comment]
have a look at image2 screenshot

**Comment by pedrobaeza** [comment]
Problem can be with _website_event_sale_ coexistence. Can you try without it?

**Comment by rafaelbn** [comment]
I have test same workflow with no issue. If you don't have ticket you got a message "No seat available"

**Comment by sandraMARIONEX** [comment]
Hello! 
Effectively, 
1/ If I do not define a ticket type and no max available seats is defined, I receive in the event page: the same message" No seat available". ---->OK

2/ If I do not define a ticket type and a max available seat is defined, it is Ok in the event page: I may select how many free tickets BUT new problem: (email). Note that my user/partner HAS an email address....
Here is the stack trace (email problem). 
Traceback (most recent call last):
  File "/home/openerp-sandbox8/instance/parts/odoo/addons/website/models/ir_http.py", line 171, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/addons/base/ir/ir_http.py", line 138, in _handle_exception
    return request._handle_exception(exception)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/addons/base/ir/ir_http.py", line 164, in _dispatch
    result = request.dispatch()
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 677, in dispatch
    r = self._call_function(*_self.params)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/home/openerp-sandbox8/instance/parts/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/home/openerp-sandbox8/instance/website/website_event_register_free/controllers/website_event.py", line 52, in event_register_free
    partner_id=http.request.env.user.partner_id.id)
  File "/home/openerp-sandbox8/instance/website/website_event_register_free/model/event_registration.py", line 33, in _prepare_registration
    'email': post['email'],
KeyError: 'email'

3/ I define a ticket type (0 euros) and no max seats is defined: in the event page: sold out----->OK

4/ I define a ticket type (0 euros) and max seats is defined: I may order free tickets.

BUT: I noticed now that even a Sales order of 0 euros is created, registrations are recorded into the event. No invoicing is required; This is exactly what we want to avoid. 

Yes the event_sales module is installed.

Could you please help for email problem (see 3/)

MANY THANKS to you all....

**Comment by pedrobaeza** [comment]
Install the new module _website_event_register_free_with_sale_

**Comment by sandraMARIONEX** [comment]
Thanks Pedro! it works. now, no more "pay now" for 0 euros!

**Comment by jbgraffiti** [comment]
hi

 I get exactly this issue (v.8) ONLY when I have created a duplicate event from the drop down menu.
" ('ValidateError', u'Error while validating constraint\n\nNo more available seats.')"

-original event - works with user logged on - max seats specified, no ticket type. free ticket, user registered
- duplicate copy of original event - exactly the same but traceback error

![Internal_Server_Error](https://user-images.githubusercontent.com/41232670/58541180-d52bd880-81f2-11e9-8be5-467a6dc2f52c.jpg)

Please advise

Many thanks Jon

training.baxterthompson.com
