### ISSUE TITLE
[8.0] [website_portal_sale] 500: Internal Server Error

### ISSUE THREAD

**Issue by insideth** [OCA/website#174]
Viewing an invoice

Example URL: www.mysite.com/report/pdf/account.report_invoice/29

Error message: list index out of range

Dump: 

`Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 666, in _handle_exception
    be used as response."""
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/openerp/http.py", line 684, in dispatch
    return Response(status=200, headers=headers)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    if self._cr:
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    @functools.wraps(f)
  File "/opt/odoo/odoo/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 256, in wrapper
``@returns(model)``.
  File "/opt/odoo/odoo/addons/report/models/report.py", line 191, in get_pdf
    if html is None:
  File "/opt/odoo/odoo/openerp/api.py", line 256, in wrapper
``@returns(model)``.
  File "/opt/odoo/odoo/addons/report/models/report.py", line 168, in get_html
    except KeyError:
  File "/opt/odoo/odoo/openerp/api.py", line 256, in wrapper
``@returns(model)``.
  File "/opt/odoo/odoo/addons/report/models/report.py", line 507, in _get_report_from_name
    conditions = [('report_type', 'in', qwebtypes), ('report_name', '=', report_name)]
IndexError: list index out of range`

**Comment by rafaelbn** [comment]
I close as error doesn't occur

http://3143034-8-0-f0e589.runbot1.odoo-community.org/my/home

![2016-03-07_22-00-39](https://cloud.githubusercontent.com/assets/8736623/13583138/1ba02750-e4b0-11e5-81c0-a850dab0b750.png)

**Comment by rafaelbn** [comment]
@insideth please reproduce error in runbot, thanks!
