### ISSUE TITLE
[8.0][website_slide] 403: Forbidden

### ISSUE THREAD

**Issue by collex100** [OCA/website#222]
module: website_slides
version: 8.0

**Steps to reproduce**
Install the module and go to the page which should open the home page slide.

On the demo page:
http://3150062-8-0-2e960e.runbot2.odoo-community.org/slides
there is a warning
403: Forbidden
When I installed I got the same warning.

**Current behavior**
403: Forbidden

**Expected behavior**
Homepage slide

Please tell me how to fix it? Thank you!

**Comment by rafaelbn** [comment]
Tested in runbot: http://3150084-8-0-958eb6.runbot1.odoo-community.org/slides

I tried also with admin user and same error:

```
Error

Error message:

Traceback

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/http.py", line 672, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/http.py", line 690, in dispatch
    r = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/addons/website_slides/controllers/main.py", line 60, in slides_index
    [], order='sequence, id')
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/models.py", line 1646, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/models.py", line 4702, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/models.py", line 3527, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150084-8-0-958eb6/openerp/addons/base/ir/ir_model.py", line 769, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Public\n\t- Portal\n\t- Human Resources/Employee\n\n(Document model: slide.channel)')
```

**Comment by rafaelbn** [comment]
Hi @collex100 if you try in a base database the error doesn't happens. So it look that some module breaks functionality. Check here:

http://3150084-8-0-958eb6.runbot1.odoo-community.org and select a base database.

**Comment by rafaelbn** [comment]
Hi @Yajo , this issue is because https://github.com/OCA/website/tree/8.0/website_seo_redirection. Please fix it. @collex100 If you uninstall that module it works!

cc @pedrobaeza @sergio-teruel

**Comment by collex100** [comment]
Thanks a lot! The module is works!

**Comment by yajo** [comment]
Please see #240

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/website/pull/240
