### ISSUE TITLE
Website title cannot update

### ISSUE THREAD

**Issue by Shiraj-Nisus** [OCA/website#292]
We have used this module for ULR redirection and works fine.Recently I have noticed that Page Title doesn't update and I have uninstalled this module for testing.Once it removed from the system I could able to renamed/update page titles under "SEO optimize".Hope this is a bug/issue and may be specific to EN version.

Tested on Odoo V9 Enterprise version

**Comment by pawanpandeyenuke** [comment]
Hi

I am getting the same issue on my website and did not find any solution. Did you find any solution?

**Comment by Shiraj-Nisus** [comment]
Hi @pawanpandeyenuke 

Yes I have solved the issue by doing a trick.Here how I did that.

Export all your URL redirection in to csv or excel
Remove all URL redirections
Uninstall the module
Clean cache (if needed)
Correct website titles
Install redirection module
import exported URLs

This way I got it to work.Hopefully developers will fix the issue with next release.

**Comment by thilina570** [comment]
I'm getting the same error. 
**Can't edit the page title after installing SEO-Redirection**
I have tested this on both odoo V9 Enterprise and Community. Both gives the same error. 
When I try to edit the SEO stuff and save, the firebug console gives 

> session.model is not a function
in website.assets_editor.js: line 283:8 
Save button just not working.

**Comment by pedrobaeza** [comment]
@Yajo, can you check?

**Comment by yajo** [comment]
> in website.assets_editor.js: line 283:8

This is useless, can you provide the logs when you are in debug mode? (Add `?debug=1` to your URL).

**Comment by thilina570** [comment]
@Yajo  got the log 
This thing works on home page, but happen on other pages
2017-01-17 09:10:46,063 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:46] "GET /page/test2 HTTP/1.1" 200 -
2017-01-17 09:10:53,549 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:53] "POST /web/dataset/call HTTP/1.1" 200 -
2017-01-17 09:10:53,622 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:53] "POST /web/dataset/call HTTP/1.1" 200 -
2017-01-17 09:10:53,674 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:53] "POST /web/dataset/call HTTP/1.1" 200 -
2017-01-17 09:10:54,049 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:54] "POST /website/translations HTTP/1.1" 200 -
2017-01-17 09:10:54,180 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:54] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2017-01-17 09:10:54,398 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:10:54] "POST /web/dataset/call_kw/web.planner/render HTTP/1.1" 200 -
2017-01-17 09:11:07,471 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:11:07] "POST /web/dataset/call_kw/ir.ui.view/read HTTP/1.1" 200 -
2017-01-17 09:11:07,565 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:11:07] "POST /web/dataset/call_kw HTTP/1.1" 200 -
2017-01-17 09:11:07,796 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:11:07] "POST /website/seo_suggest HTTP/1.1" 200 -
2017-01-17 09:11:10,088 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:11:10] "POST /longpolling/poll HTTP/1.1" 200 -
2017-01-17 09:11:10,089 1392 ERROR thilina openerp.service.server: Exception happened during processing of request from ('127.0.0.1', 51931)
Traceback (most recent call last):
  File "SocketServer.pyc", line 599, in process_request_thread
  File "SocketServer.pyc", line 334, in finish_request
  File "SocketServer.pyc", line 657, in __init__
  File "SocketServer.pyc", line 716, in finish
  File "socket.pyc", line 283, in close
  File "socket.pyc", line 307, in flush
error: [Errno 10053] An established connection was aborted by the software in your host machine

**Comment by yajo** [comment]
I mean the JS log. And please remember to write the logs between triple-backticks to get them easier to read 😉. Like this:

    ```
    [The logs]
    ```

**Comment by thilina570** [comment]
Sorry about that formatting.
I found out this actually saving the page when I click "Discard" :) on 'Promote This Page' pop-up.
I couldn't fiend any JS log. I think you mean fire-bug console out-put? This is what it's giving. I agree with you it cannot be in this js as it's core odoo js file I think. 
```
TypeError: session.model is not a function[Learn More]  website.assets_editor.js:283:8
```
My friend said this module works fine in odoo 10.
Here is the openerp-server.log again with formating 
```
2017-01-17 09:22:09,848 1392 INFO thilina werkzeug: 127.0.0.1 - - [17/Jan/2017 09:22:09] "POST /longpolling/poll HTTP/1.1" 200 -
2017-01-17 09:22:09,848 1392 ERROR thilina openerp.service.server: Exception happened during processing of request from ('127.0.0.1', 52469)
Traceback (most recent call last):
  File "SocketServer.pyc", line 599, in process_request_thread
  File "SocketServer.pyc", line 334, in finish_request
  File "SocketServer.pyc", line 657, in __init__
  File "SocketServer.pyc", line 716, in finish
  File "socket.pyc", line 283, in close
  File "socket.pyc", line 307, in flush
error: [Errno 10053] An established connection was aborted by the software in your host machine
```

**Comment by yajo** [comment]
Please, read carefully: I need the JS logs with `?debug=1` in the URL.

**Comment by thilina570** [comment]
I think this is you are asking. 
```
.update_seo_redirection http://localhost:8069/web/content/569-ce10f12/website.assets_editor.js:283:8
.saveMetaData http://localhost:8069/web/content/569-ce10f12/website.assets_editor.js:282:583
OdooClass.extend/Class.include/</prototype[name]</< http://localhost:8069/web/content/385-fe942d6/web.assets_common.js:2536:368
Configurator<.update http://localhost:8069/web/content/569-ce10f12/website.assets_editor.js:175:1
Widget<.proxy/< http://localhost:8069/web/content/385-fe942d6/web.assets_common.js:2644:8
jQuery.event.dispatch http://localhost:8069/web/content/385-fe942d6/web.assets_common.js:740:378
jQuery.event.add/elemData.handle http://localhost:8069/web/content/385-fe942d6/web.assets_common.js:713:151
```

**Comment by creativelabslk** [comment]
Any update on this. I'm stuck with the same issue here. :(

**Comment by pedrobaeza** [comment]
There isn't any still any JS log with debug mode activated as far as I see.

**Comment by yajo** [comment]
Please reopen if this still happens and you can provide the debug logs, thanks!
