### ISSUE TITLE
website_legal_page 10.0 causes error on first request after restart

### ISSUE THREAD

**Issue by rabchev** [OCA/website#389]
When website_legal_page is present in extensions, after restart the first request to the server return internal server error response and the following error is logged:

2017-10-05 01:29:03,589 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 184, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 144, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1307, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1328, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/mnt/extra-addons/website_legal_page/__init__.py", line 4, in <module>
    from . import controllers
  File "/mnt/extra-addons/website_legal_page/controllers/__init__.py", line 4, in <module>
    from . import main
  File "/mnt/extra-addons/website_legal_page/controllers/main.py", line 7, in <module>
    from six import raise_from
ImportError: cannot import name raise_from

The error appears only on the first request, any subsequent requests are ok. It appears even if the module is not installed in Odoo. The problem disappears if I remove the extension.

**Comment by pedrobaeza** [comment]
This is because you haven't installed six library or proper version of it.
