### ISSUE TITLE
 website_sale_vat_required.saas_users

### ISSUE THREAD

**Issue by MiguelMachadoM** [OCA/website#39]
Error:

```
500: Internal Server Error
Error

Mensaje de error:

Element '<label class="control-label" for="vat" data-oe-id="1725" data-oe-source-id="1506" data-oe-xpath="/data/label" data-oe-model="ir.ui.view" data-oe-field="arch">' cannot be located in parent view

Error context:
View `saas_users`
[view_id: 1725, xml_id: website_sale_vat_required.saas_users, model: n/a, parent_id: 1506]
```

This happens when I'm logged in as (in this case root).
When I register as a new user no problem, the problem occurs when I am already a registered user and try make a order in shop.

Trace:

```
Traceback (most recent call last):
  File "/opt/odoo/8.0/core/addons/website/models/ir_http.py", line 196, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_http.py", line 146, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/8.0/core/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/8.0/core/openerp/http.py", line 1358, in get_response
    result.flatten()
  File "/opt/odoo/8.0/core/openerp/http.py", line 1231, in flatten
    self.response.append(self.render())
  File "/opt/odoo/8.0/core/openerp/http.py", line 1225, in render
    context=request.context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/addons/website/models/ir_ui_view.py", line 172, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 1029, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_qweb.py", line 261, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_qweb.py", line 190, in get_template
    xml_doc = qwebcontext.loader(name)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 1027, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in read_template
  File "/opt/odoo/8.0/core/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 859, in read_template
    arch = self.read_combined(cr, uid, view_id, fields=['arch'], context=context)['arch']
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 553, in read_combined
    cr, uid, arch_tree, root_id, base.model, context=context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 506, in apply_view_inheritance
    source = self.apply_inheritance_specs(cr, uid, source, specs_tree, view_id, context=context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 484, in apply_inheritance_specs
    self.raise_view_error(cr, uid, _("Element '%s' cannot be located in parent view") % tag, inherit_id, context=context)
  File "/opt/odoo/8.0/core/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/core/openerp/addons/base/ir/ir_ui_view.py", line 369, in raise_view_error
    raise AttributeError(message)
AttributeError: Element '<label class="control-label" for="vat" data-oe-id="1725" data-oe-source-id="1506" data-oe-xpath="/data/label" data-oe-model="ir.ui.view" data-oe-field="arch">' cannot be located in parent view

Error context:
View `saas_users`
[view_id: 1725, xml_id: website_sale_vat_required.saas_users, model: n/a, parent_id: 1506]
```

**Comment by MiguelMachadoM** [comment]
@eLBati you can check this?

any idea?

**Comment by MiguelMachadoM** [comment]
@eLBati  
Well i Deactivate this view and now work without errors.

**Comment by eLBati** [comment]
Hello @Razztak 
the PR https://github.com/OCA/website/pull/57 should fix it

**Comment by rafaelbn** [comment]
Please @Razztak could you test this issue again and if solved as @eLBati says close this issue? Thanks

**Comment by pedrobaeza** [comment]
I close it because it should be. If not, feel free to reopen again.
