### ISSUE TITLE
[11.0] website_multi_theme doesn't open html editor

### ISSUE THREAD

**Issue by lucode** [OCA/website#483]
When I install the actual version 11.0.1.4.0 I can't open the frontend html editor. Doesn't matter which theme I use. 
We figured out to make the editor visible again, but unfortunately only footer and header elements are shown. We did replace:
line 44 in website_multi_theme/models/ir_ui_view.py:​
from this:
`​current_website = request.website`
​to this:
`​current_website = self.env['website'].get_current_website() `

**Comment by lucode** [comment]
A workaround is to use the /content/manage page page form and edit the pages in the backend.

**Comment by yelizariev** [comment]
Log message
```

Traceback (most recent call last):
  File "/mnt/odoo-source/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/odoo-source/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/odoo-source/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/odoo-source/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/odoo-source/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-source/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-source/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-source/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-source/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-source/addons/web_editor/controllers/main.py", line 240, in get_assets_editor_resources
    views = request.env["ir.ui.view"].get_related_views(key, bundles=bundles)
  File "/mnt/addons/OCA/website/website_multi_theme/models/ir_ui_view.py", line 44, in get_related_views
    current_website = request.website
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'JsonRequest' object has no attribute 'website'

```

**Comment by yelizariev** [comment]
I'm going to propose a fix to odoo directly

**Comment by yelizariev** [comment]
The code where error is raised:

https://github.com/OCA/website/blob/963de01/website_multi_theme/models/ir_ui_view.py#L37-L45

**Comment by yelizariev** [comment]
the fix in https://github.com/odoo/odoo/pull/25347

If they don't accept it, we can make a workaround directly in ``website_multi_theme`` module.

cc @Yajo

**Comment by yajo** [comment]
Good idea.

**Comment by yelizariev** [comment]
Fixed in odoo

**Comment by pedrobaeza** [comment]
Closing then. A commit reference would be good.
