### ISSUE TITLE
Collapsible product categories in website shop causing NoneType error

### ISSUE THREAD

**Issue by beergirlatl** [OCA/website#51]
I have successfully installed the module (without error) to create collapsible categories in the webshop, but when I navigate to the Customize menu and select the check box, the shop page shows this error.  

I am suspecting that this is some sort of null data error, but not sure where/what might be missing?  I have many categories with parent categories, and every product in the system has a public category defined.  

Any suggestions on where to look would be much appreciated.

Oh, I am running odoo on Windows 8 and despite the file structure I am current up to the odoo_8.0.20150625 build.

![screenhunter_65 jul 01 15 17](https://cloud.githubusercontent.com/assets/11587862/8462820/66d65f6c-2004-11e5-93fb-96fe1959e556.jpg)
![screenhunter_66 jul 01 15 23](https://cloud.githubusercontent.com/assets/11587862/8462952/36312e90-2005-11e5-8d88-4670a324156d.jpg)

Error
Error message:

"argument of type 'NoneType' is not iterable" while evaluating
"'fa-chevron-down' if categ.id in parent_category_ids else 'fa-chevron-right'"
QWeb
Error message:

Could not evaluate expression "'fa-chevron-down' if categ.id in parent_category_ids else 'fa-chevron-right'"
The error occured while rendering the template website_sale_collapse_categories.option_collapse_categories_recursive and evaluating the following expression: 'fa-chevron-down' if categ.id in parent_category_ids else 'fa-chevron-right'

Traceback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\website\models\ir_http.py", line 199, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_http.py", line 147, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\http.py", line 666, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\http.py", line 1368, in get_response
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\http.py", line 1241, in flatten
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\http.py", line 1235, in render
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\website\models\ir_ui_view.py", line 172, in render
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_ui_view.py", line 1029, in render
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 261, in render
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 298, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 436, in render_tag_call
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 298, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 422, in render_tag_foreach
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 298, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 445, in render_tag_call
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 261, in render
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 300, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 321, in render_element
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 283, in render_node
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\website\models\ir_qweb.py", line 61, in render_att_att
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 354, in render_att_att
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 223, in eval_format
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 222, in <lambda>
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 213, in eval_str
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 205, in eval
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 202, in eval
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server\openerp\addons\base\ir\ir_qweb.py", line 88, in safe_eval
  File "C:\Program Files (x86)\Odoo 8.0-20141003-000212\server.\openerp\tools\safe_eval.py", line 314, in safe_eval
  File "", line 1, in <module>
QWebException: "argument of type 'NoneType' is not iterable" while evaluating
"'fa-chevron-down' if categ.id in parent_category_ids else 'fa-chevron-right'"

**Comment by pedrobaeza** [comment]
Try to reproduce the problem in one instance of runbot: https://runbot.odoo-community.org/runbot/repo/github-com-oca-website-186, and tell us the sequence, because I haven't get that problem. Have you customized something (theme, code...)?

**Comment by beergirlatl** [comment]
I haven't customized anything myself.  Just trying to set up the website at this point, however I did notice that I have a few more modules installed, like Point of Sale, Accounting, Projects, etc.

**Comment by pedrobaeza** [comment]
Please try in the link above if you can reproduce the problem. If then, please write down the followed steps.

**Comment by beergirlatl** [comment]
I have not been able reproduce the problem in your instance.  In my own instance I have deleted all Public Categories and the Shop loads without generating the error.  However, when I create a Public Category and navigate back to the Shop, the error reappears,  even if I haven't added the Public Category to any product records or changed anything else.  It looks like there are some permission differences between your instance and mine on the product.public.category model, namely that my instance looks to be requiring the "name" field and makes "__last_update", "complete_name", "display_name", and "id" Readonly whereas your instance shows nothing required or readonly (including screenshots).  Do you think it is possible that this could be contributing to the problem or is there another module that might have altered these settings that I should install or uninstall?  
Any guidance would be greatly appreciated.

![bg instance product public category model](https://cloud.githubusercontent.com/assets/11587862/8710838/d922feb0-2b1a-11e5-82d0-ceb6d9ef4bbb.jpg)
![pedro instance product public category model](https://cloud.githubusercontent.com/assets/11587862/8710912/4ca1bade-2b1b-11e5-9ea1-57b9ff0adaa4.jpg)

**Comment by pedrobaeza** [comment]
Sorry, but we need that the bug is reproducible in our side, so I close meanwhile.

**Comment by Snarfbox** [comment]
Hello, I have the same problem. I'm on Ubuntu with the last versions of odoo8

**Comment by shahid-malik** [comment]
Anyone got the solution of the problem ?

**Comment by gonxi** [comment]
in my case the problem is solved moving the website_product_filters module from vauxoo out of addons path. (this module was donwloaded from "Apps in line")
https://apps.odoo.com/apps/modules/8.0/website_product_filters/
is possible that you have this module?

**Comment by treviser** [comment]
The problem exists in all versions from 8.0 to 11.0 and this happens when the module website_product_brand module is installed together with collapsible/expandable categories. Somebody with a kyrillic name has posted a comment on the App store page where he assumed that this happens because of inheriting the same controller, see his comments here: https://apps.openerp.com/apps/modules/8.0/website_product_brand/
If I deactivate the option for expandable/collapsible categories in the shop page, website_product_brand works perfectly.
Is there anything which can be done about it?

**Comment by pedrobaeza** [comment]
I don't think the problem is in versions >v8, as the feature is integrated in core, with no multiple inheritance. For v8, the only way I see is to add a glue module.

**Comment by ayobello** [comment]
I have just encountered this issue in v12. Anyone found a permanent solution yet?
