### ISSUE TITLE
website_lazy_load_image: translation broken after install

### ISSUE THREAD

**Issue by thanhacun** [OCA/website#551]
After installing the module, all translation (other than default) is broken (in my case, it is Vietnamese) for the website module:

- The translation is OK if a user is logged in
- The translation is Broken if a public user

Please see the attached  file for the website menu

![annotation 2018-12-12 113918](https://user-images.githubusercontent.com/7599781/49847431-9f409680-fe02-11e8-8317-6f6dea51a915.jpg)

Our temporary solution:
- Using unicode parser in /model/ir_ui_view.py file
`unicode_parser = etree.HTMLParser(encoding='utf-8')`
`...`
`html = etree.HTML(res, parser=unicode_parser)`

**Comment by pedrobaeza** [comment]
Which module? Which version?

**Comment by thanhacun** [comment]
Module: oca/website/website_lazy_load_image
Version: 11.0.1.0.0

Behavior:
- After installing the module, translation for Vietnamese (I had only
English and Vietnamese translations) in the website is broken
- It only effects when not login (public users)

Temporary fix:
- In oca/website/website_lazy_load_image/models/ir_ui_view.py file, replace:
   html = etree.HTML(res) with
   html = etree.HTML(res, parser=etree.HTMLParser(encoding='utf-8'))

Thank you and best regards,

Truong Quang Thanh
mob.: +84-94-806-3388

**Comment by simahawk** [comment]
@tarteo ping :)

**Comment by tarteo** [comment]
Thanks @thanhacun, your fix seems to be the solution. Can you make a PR with your fix, please.

**Comment by thanhacun** [comment]
Hi Dennis,

I just found another  problem:
- After installing the module, both original one, and my-temporary-one:
robots.txt file is invalid according to Google Audit Lighthouse tool

- And I still do not know how to do!

Best regards,

Truong Quang Thanh
mob.: +84-94-806-3388

**Comment by tarteo** [comment]
@thanhacun What is the error you get at Google Audit Lighthouse tool? I don't think it's related to the lazy loading module because it doesn't alter the robots.txt or sitemap.xml.

**Comment by aek** [comment]
This simple change fix everything

`html = etree.fromstring(res)`

There is no need for more I think. I have test it and it works as expected. 
The usage of `etree.HTML` seems to add the html structure of `<html><body></body></html>` to enclose the rendered template and that breaks others stuffs.

**Comment by simahawk** [comment]
@aek can you propose a PR and a test to precisely check that we get only the markup we expect?

**Comment by munruf** [comment]
Hi guys I have checked both methods:
No one is provide full solution:
The issue is absolutely same, I'm using English as a primary language for website and Russian as translation.
1. change html = etree.HTML(res) with html = etree.HTML(res, parser=etree.HTMLParser(encoding='utf-8')) 
fixed the issue
2. html = etree.fromstring(res) 
geting internal server error:
___________
2019-02-06 01:20:35,403 1 ERROR kitcherie.com odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 830, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1270, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1263, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/mnt/extra-addons-oca/website_lazy_load_image/models/ir_ui_view.py", line 27, in render_template
    html = etree.fromstring(res)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "<string>", line 249
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: br line 249 and p, line 249, column 65

**Comment by simahawk** [comment]
the solution I proposed on https://github.com/OCA/website/pull/571 seems to play nice w/ translations too.
NOTE: part of the issues (wrapping elem) reported here is related and handled by #571 
Can you guys test it in your context?

**Comment by hugho-ad** [comment]
Hi, could you test following pr 
https://github.com/OCA/website/pull/651
