### ISSUE TITLE
[10.0] website_legal_lage - ImportError: cannot import name raise_from

### ISSUE THREAD

**Issue by miqmago** [OCA/website#619]
I'm also having issues with six in odoo-10.
Error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1307, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1328, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/mnt/extra-addons/website_legal_page/__init__.py", line 4, in <module>
    from . import controllers
  File "/mnt/extra-addons/website_legal_page/controllers/__init__.py", line 4, in <module>
    from . import main
  File "/mnt/extra-addons/website_legal_page/controllers/main.py", line 7, in <module>
    from six import raise_from
ImportError: cannot import name raise_from
```

This is the environment (after upgrading python 2.7.9 -> 2.7.16, to see if this resolves the issue):

```bash
root@daf5cdf2c1ab:/# python --version
Python 2.7.16
```

```bash
root@daf5cdf2c1ab:/# pip list
argh (0.25.0)
argparse (1.2.1)
Babel (1.3)
chardet (2.3.0)
colorama (0.3.2)
decorator (3.4.0)
docutils (0.12)
feedparser (5.1.3)
gevent (1.0.1)
greenlet (0.4.2)
html5lib (0.999)
Jinja2 (2.7.3)
lxml (3.4.0)
Mako (1.0.0)
MarkupSafe (0.23)
mock (1.0.1)
odoo (10.0.post20171030)
passlib (1.6.1)
pathtools (0.1.2)
Pillow (2.6.1)
pip (1.5.6)
psutil (2.1.1)
psycogreen (1.0)
psycopg2 (2.5.4)
PyChart (1.39)
pydot (1.0.32)
pyparsing (2.0.3)
pyPdf (1.13)
python-dateutil (2.2)
python-ldap (2.4.10)
python-openid (2.2.5)
python-stdnum (1.0)
pytz (2012rc0)
PyYAML (3.11)
reportlab (3.1.8)
requests (2.4.3)
roman (2.0.0)
setuptools (41.0.1)
six (1.12.0)
suds (0.4.1)
Unidecode (1.0.23)
urllib3 (1.9.1)
vatnumber (1.2)
vobject (0.8.1rc0)
watchdog (0.7.0)
Werkzeug (0.9.6)
wsgiref (0.1.2)
XlsxWriter (0.5.2)
xlwt (0.7.5)
```

**Comment by pedrobaeza** [comment]
Sorry, but this is something in your deployment, not of the module itself. Install six properly.
