### ISSUE TITLE
[12] [website_no_crawler] error when get robots.txt

### ISSUE THREAD

**Issue by luisplanes** [OCA/website#677]
When get robots.txt directly browser odoo reponse with Internal Server Error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/server.py", line 434, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/addons/http_routing/models/ir_http.py", line 403, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo/addons/website/models/ir_http.py", line 195, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/opt/odoo/odoo/odoo/http.py", line 1270, in flatten
    self.response.append(self.render())
  File "/opt/odoo/odoo/odoo/http.py", line 1263, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 1304, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo/addons/website/models/ir_ui_view.py", line 315, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 1313, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-54>", line 2, in compile
    
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_qweb.py", line 114, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 292, in compile
    element, document = self.get_template(template, options)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 392, in get_template
    raise QWebException("Template not found", name=template)
odoo.addons.base.models.qweb.QWebException: None
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/opt/odoo/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7febe2abd268>, 434, ('es_ES', None, None, None, None, None))
Template not found
Template: 434 - - -
```

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in runbot.

**Comment by colmeirin** [comment]
Hello, I reproduced the same issue in an custom enviroment and runbot.
In runbot just go to runbot and ask for /robots.txt and it will fail
<img width="995" alt="Captura de pantalla 2020-02-19 a las 17 31 57" src="https://user-images.githubusercontent.com/5647643/74853335-12666680-533e-11ea-8e98-6e5d813a3c30.png">

It seems an inheritance bug. It can be properly generated swaping:

`<xpath expr="." position="replace">
with
<xpath expr="t" position="replace">`
at file [https://github.com/OCA/website/blob/f4782ffe0f64be33b5c6b18d78e8fddfd81190b0/website_no_crawler/views/disable_robots.xml#L4](url)

**Comment by pedrobaeza** [comment]
Are there several databases without dbfilter?

**Comment by colmeirin** [comment]
At my custom enviroment, no. It's the only database. And at runbot seems like it is also the only database:
<img width="938" alt="Captura de pantalla 2020-02-19 a las 17 43 47" src="https://user-images.githubusercontent.com/5647643/74854312-776e8c00-533f-11ea-99d1-7fa20a7385dd.png">

**Comment by pedrobaeza** [comment]
Please put the link to that runbot. And the inheritance problem you mention, with which module is interacting bad?

**Comment by colmeirin** [comment]
link to runbot: [http://3404981-12-0-f4782f.runbot1-2.odoo-community.org/](url)
add /robots.txt and it will fail.
the module is OCA/website/website_no_crawler.
This is the original view:
<img width="917" alt="Captura de pantalla 2020-02-19 a las 17 50 44" src="https://user-images.githubusercontent.com/5647643/74855437-fd3f0700-5340-11ea-843d-8b29cb64ef50.png">
and it's defined at odoo core "website" module [https://github.com/odoo/odoo/blob/d039847b3df1941626425ee474788fcecd230168/addons/website/views/website_templates.xml#L1065](url)

**Comment by pedrobaeza** [comment]
OK, I see. Do you please make the PR fixing it?

**Comment by colmeirin** [comment]
Fix has been merged. Maybe you can close the issue. Regards!
